### ISSUE TITLE
Crash when editing property description

### ISSUE THREAD

**Issue by pruje** [onmyshelf/onmyshelf#54]
```
[FATAL] TypeError: array_keys(): Argument #1 ($array) must be of type array, string given in /var/www/html/api/v1/inc/database/sqlDatabase.php:283
Stack trace:
#0 /var/www/html/api/v1/inc/database/sqlDatabase.php(283): array_keys()
#1 /var/www/html/api/v1/inc/database/sqlDatabase.php(937): SqlDatabase->labelToDB()
#2 /var/www/html/api/v1/inc/classes/Property.php(54): SqlDatabase->updateProperty()
#3 /var/www/html/api/v1/inc/api.php(943): Property->update()
#4 /var/www/html/api/v1/inc/api.php(291): Api->routeCollectionsIdPropertiesName()
#5 /var/www/html/api/v1/index.php(8): Api->route()
#6 {main}
```

**Comment by pruje** [comment]
Fixed in commit https://github.com/onmyshelf/web/commit/d8101512086a88e20825076e9efb0de2cf822543
