### ISSUE TITLE
Error when migrating from stable to nightly

### ISSUE THREAD

**Issue by IkariTyux** [onmyshelf/onmyshelf#70]
Hi there,
I tried to change my .env from default to nightly and it's not working.

Here are the line that i got in the docker-compose logs.

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause' in /var/www/html/api/v1/inc/database/sqlDatabase.php:1415
server-1  | Stack trace:
server-1  | #0 /var/www/html/api/v1/inc/database/sqlDatabase.php(1415): PDOStatement->execute()
server-1  | #1 /var/www/html/api/v1/inc/database/sqlDatabase.php(1463): SqlDatabase->select()
server-1  | #2 /var/www/html/api/v1/inc/database/sqlDatabase.php(1483): SqlDatabase->selectFirst()
server-1  | #3 /var/www/html/api/v1/inc/database/sqlDatabase.php(1324): SqlDatabase->selectOne()
server-1  | #4 /var/www/html/api/v1/inc/database/sqlDatabase.php(1350): SqlDatabase->install()
server-1  | #5 /var/www/html/api/v1/bin/oms(87): SqlDatabase->upgrade()
server-1  | #6 /var/www/html/api/v1/bin/oms(180): Cmd::upgrade()
server-1  | #7 {main}
server-1  |   thrown in /var/www/html/api/v1/inc/database/sqlDatabase.php on line 1415
```

Have a nice day.

**Comment by pruje** [comment]
Thanks for your bug report!
Bug has been fixed in this commit: https://github.com/onmyshelf/api/commit/835ad09176cbeec57bbf817c1b88c2dc4562b9f0
The nightly image has also been pushed to the docker hub, so you can retry now.

**Comment by IkariTyux** [comment]
Yup, it works fine ... on a fresh installation. 
When i try to change my existing one from the stable to nightly version, it doesn't work.
The docker create and starts without issue, but I can't access the website.

![screenshot_2024-02-22T21:17:18](https://github.com/onmyshelf/onmyshelf/assets/160258025/f4be7f0d-4312-471b-83e4-58a8cc4b96f6)

```
server-1  | OnMyShelf is already installed
server-1  | Upgrading from 1.0.1 to 1.1.0-rc.2...
server-1  | Create missing tables...
server-1  | PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause' in /var/www/html/api/v1/inc/database/sqlDatabase.php:1415
server-1  | Stack trace:
server-1  | #0 /var/www/html/api/v1/inc/database/sqlDatabase.php(1415): PDOStatement->execute()
server-1  | #1 /var/www/html/api/v1/inc/database/sqlDatabase.php(1463): SqlDatabase->select()
server-1  | #2 /var/www/html/api/v1/inc/database/sqlDatabase.php(1483): SqlDatabase->selectFirst()
server-1  | #3 /var/www/html/api/v1/inc/database/sqlDatabase.php(1324): SqlDatabase->selectOne()
server-1  | #4 /var/www/html/api/v1/inc/database/sqlDatabase.php(1350): SqlDatabase->install()
server-1  | #5 /var/www/html/api/v1/bin/oms(87): SqlDatabase->upgrade()
server-1  | #6 /var/www/html/api/v1/bin/oms(180): Cmd::upgrade()
server-1  | #7 {main}
server-1  |   thrown in /var/www/html/api/v1/inc/database/sqlDatabase.php on line 1415
```

**Comment by pruje** [comment]
Did you tried to pull image again?
```
docker compose pull
docker compose up -d
```

**Comment by IkariTyux** [comment]
Nope

**Comment by IkariTyux** [comment]
It works now !

**Comment by pruje** [comment]
OK fine. I will complete the admin guide in official documentation to cover this case.

**Comment by pruje** [comment]
Documentation added in docker project [here](https://github.com/onmyshelf/docker?tab=readme-ov-file#upgrade-with-docker-compose)
